ci: update github actions

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -48,6 +48,14 @@ jobs:
         key: ${{ secrets.EC2_SSH_KEY }}
         envs: ECR_REGISTRY,ECR_REPOSITORY,IMAGE_TAG,CONTAINER_NAME,AWS_REGION
         script: |
+          echo "Debug: Region is $AWS_REGION"
+          echo "Debug: Region is $AWS_REGISTRY"
+
+          if [ -z "$ECR_REGISTRY" ]; then
+            echo "ERROR: ECR_REGISTRY variable is empty"
+            exit 1
+          fi
+          
           aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
 
           docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
